import {
  Archive,
  ArrowLeft,
  Bell,
  BellOff,
  Bookmark,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronRight,
  CircleAlert,
  Copy,
  Database,
  FileUp,
  Forward,
  Folder,
  FolderPlus,
  Globe2,
  Info,
  KeyRound,
  LoaderCircle,
  LogIn,
  MessageCircle,
  MessageSquare,
  Mic,
  MoreHorizontal,
  Phone,
  Pin,
  Pencil,
  Plus,
  Reply,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Star,
  Trash2,
  UserRound,
  UserRoundPlus,
  Video,
  X,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  add: Plus,
  archive: Archive,
  arrow_back: ArrowLeft,
  attach_file: FileUp,
  bookmark: Bookmark,
  chat: MessageCircle,
  chat_bubble: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  close: X,
  content_copy: Copy,
  create_new_folder: FolderPlus,
  database: Database,
  delete: Trash2,
  done_all: CheckCheck,
  edit: Pencil,
  error: CircleAlert,
  forward: Forward,
  folder: Folder,
  key: KeyRound,
  language: Globe2,
  login: LogIn,
  mic: Mic,
  mood: Smile,
  more_horiz: MoreHorizontal,
  notifications: Bell,
  notifications_off: BellOff,
  person: UserRound,
  person_add: UserRoundPlus,
  phone: Phone,
  progress_activity: LoaderCircle,
  push_pin: Pin,
  reply: Reply,
  search: Search,
  security: ShieldCheck,
  send: Send,
  select: CheckCircle2,
  settings: Settings,
  star: Star,
  tune: SlidersHorizontal,
  videocam: Video,
  chevron_right: ChevronRight,
  info: Info,
};

type IconProps = {
  name: string;
  className?: string;
  "aria-label"?: string;
};

// #preview Icon {"name":"search"}
export function Icon({ name, className, "aria-label": ariaLabel }: IconProps) {
  const Component = icons[name] ?? CircleAlert;
  return <Component aria-hidden={ariaLabel ? undefined : true} aria-label={ariaLabel} className={className} />;
}
