import {
  Archive,
  ArrowLeft,
  ArrowRight,
  Bell,
  BellOff,
  Bookmark,
  Check,
  CheckCheck,
  CheckCircle2,
  CircleAlert,
  Copy,
  Database,
  Download,
  FileUp,
  FileText,
  Forward,
  Folder,
  Globe2,
  Gauge,
  Info,
  KeyRound,
  LogIn,
  LogOut,
  MessageCircle,
  Mic,
  MoreHorizontal,
  Pencil,
  Phone,
  Pause,
  Pin,
  Play,
  Plus,
  Reply,
  RotateCcw,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Star,
  Trash2,
  Video,
  Volume2,
  VolumeX,
  UserRound,
  X,
  type LucideIcon,
} from "lucide-react-native";

const names = {
  arrowBack: ArrowLeft,
  arrowForward: ArrowRight,
  archive: Archive,
  attach: FileUp,
  backspace: Trash2,
  bookmark: Bookmark,
  check: Check,
  checkAll: CheckCheck,
  checkCircle: CheckCircle2,
  chat: MessageCircle,
  close: X,
  copy: Copy,
  delete: Trash2,
  database: Database,
  download: Download,
  edit: Pencil,
  error: CircleAlert,
  folder: Folder,
  forward: Forward,
  globe: Globe2,
  speed: Gauge,
  info: Info,
  key: KeyRound,
  language: Globe2,
  logs: FileText,
  login: LogIn,
  logout: LogOut,
  menu: MoreHorizontal,
  mic: Mic,
  more: MoreHorizontal,
  notifications: Bell,
  notificationsOff: BellOff,
  person: UserRound,
  phone: Phone,
  pause: Pause,
  pin: Pin,
  play: Play,
  plus: Plus,
  reply: Reply,
  rotateLeft: RotateCcw,
  search: Search,
  security: ShieldCheck,
  send: Send,
  settings: Settings,
  share: Share2,
  star: Star,
  tune: SlidersHorizontal,
  videocam: Video,
  volume: Volume2,
  volumeOff: VolumeX,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof names;

export function Icon({ name, size = 20, color }: { name: IconName; size?: number; color?: string }) {
  const Component = names[name];
  return <Component size={size} color={color} strokeWidth={2} />;
}
